baseURL: https://twitter.github.io/birdwatch/
languageCode: en-us
title: Birdwatch Guide

theme: "geekdoc"

# Required to get well formatted code blocks
pygmentsUseClasses: true
pygmentsCodeFences: true
disablePathToLower: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 4

params:
  geekdocTOC: 3
  geekdocNextPrev: true
  geekdocMenuBundle: true
  geekdocLogo: "images/birdwatch-logo.png"
  geekdocBreadcrumb: false
  geekdocSearch: false
  # geekdocRepo: "https://github.com/twitter/birdwatch"
  # geekdocEditPath: "edit/main/content"
